# Generated by Django 5.1.5 on 2026-04-23 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('users', '0002_organization_user_orcid_id_user_prefs_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.organization'),
        ),
    ]
